AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0.0
  Exclude:
    - bin/*
    - doc/**/*
    - db/schema.rb
    - log/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - config/puma.rb
    - config.ru
    - Rakefile
    - config/spring.rb

Layout/TrailingWhitespace:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - db/**/*
Metrics/ClassLength:
  Max: 150
  Exclude:
    - db/**/*
Metrics/MethodLength:
  Max: 30
  Exclude:
    - db/**/*
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*
    - db/**/*
Metrics/AbcSize:
  Max: 30
  Exclude:
    - db/**/*

Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/SwapValues:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Style/HashExcept:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
